name: Java CI with Maven

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_URL: ${{ secrets.DB_URL }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
      STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
      
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: ${{ secrets.DB_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Create test directories and configuration
      run: |
        mkdir -p src/test/resources
        cat > src/test/resources/application-test.properties << EOF
        # データベース設定
        spring.datasource.url=${{ secrets.DB_URL }}
        spring.datasource.username=${{ secrets.DB_USERNAME }}
        spring.datasource.password=${{ secrets.DB_PASSWORD }}
        spring.datasource.driver-class-name=org.postgresql.Driver
        spring.jpa.hibernate.ddl-auto=create-drop
        
        # Stripe設定
        stripe.api-key=${{ secrets.STRIPE_API_KEY }}
        stripe.webhook-secret=${{ secrets.STRIPE_WEBHOOK_SECRET }}
        
        # サーバー設定
        server.port=0
        
        # ログレベル設定（トラブルシューティング用）
        logging.level.org.springframework=INFO
        logging.level.com.example=DEBUG
        EOF

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Run tests and generate reports
      run: mvn clean test site
      env:
        SPRING_DATASOURCE_URL: ${{ secrets.DB_URL }}
        SPRING_DATASOURCE_USERNAME: ${{ secrets.DB_USERNAME }}
        SPRING_DATASOURCE_PASSWORD: ${{ secrets.DB_PASSWORD }}
        STRIPE_API_KEY: ${{ secrets.STRIPE_API_KEY }}
        STRIPE_WEBHOOK_SECRET: ${{ secrets.STRIPE_WEBHOOK_SECRET }}
        SERVER_PORT: 0

    - name: Create artifact directory
      run: mkdir -p artifact_reports

    - name: Copy HTML report to artifact directory
      run: cp target/site/surefire-report.html artifact_reports/surefire-report.html || echo "No HTML report to copy"

    - name: Copy XML test results to artifact directory
      run: cp -r target/surefire-reports/*.xml artifact_reports/ || echo "No XML files to copy"

    # 現在のリポジトリへの保存
    - name: Save test reports to current repository
      if: always()
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        
        git add artifact_reports/
        git commit -m "Add test reports from CI run" || echo "No changes to commit"
        git push origin HEAD:main

    # 別リポジトリへのプッシュ（個人アクセストークンを使用）
    - name: Push report to test code repository
      if: always()
      run: |
        # コピーしてindexとして保存
        cp artifact_reports/surefire-report.html index.html
        
        # 別リポジトリのクローン（パスを指定して別フォルダにクローン）
        git clone https://${{ secrets.REPO_ACCESS_TOKEN }}@github.com/VD3baeKy/RenderOutput2_TestCodeRepo.git test-repo
        
        # ファイルをコピー
        cp index.html test-repo/
        
        # 別リポジトリにコミットとプッシュ
        cd test-repo
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Update test report" || echo "No changes to commit"
        git push
